name: Test Action
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Test Download Hugo
        uses: ./
        with:
          repo-name: 'gohugoio/hugo'
          file-name: '~hugo_extended_[^a-z]'
          token: ${{ secrets.GH_TOKEN }}

      - name: Verify Installation
        run: |
          hugo version
