name: Test Action
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go ACME Setup
        uses: ./
        with:
          repo-name: 'go-acme/lego'
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Hugo
        uses: ./
        with:
          repo-name: 'gohugoio/hugo'
          file-name: '~hugo_extended_[^a-z]'
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup RClone
        uses: ./
        with:
          repo-name: 'rclone/rclone'
          token: ${{ secrets.GH_TOKEN }}

      - name: Verify Installation
        run: |
          echo "Verifying installed tools..."
          printf "\nGo ACME Lego:\n"
          lego -v
          printf "\nHugo:\n"
          hugo version
          printf "\nRClone:\n"
          rclone version
